In [2]:
import pandas as pd

df = pd.read_csv("../data/cleaned/cleaned_movies.csv")

# Encode Certificate
cert_map = {'U':0, 'UA':1, 'A':2, 'S':3}
df['Certificate_Num'] = df['Certificate'].map(cert_map)

# Director Reputation (average gross per director)
director_avg = df.groupby('Director')['Gross'].mean()
df['Director_Reputation'] = df['Director'].map(director_avg)

# Star Power (sum of average gross per star)
stars = ['Star1','Star2','Star3','Star4']
for star in stars:
    star_avg = df.groupby(star)['Gross'].mean()
    df[star+'_Rep'] = df[star].map(star_avg)

# Combine star power into one metric
df['Star_Power'] = df[['Star1_Rep','Star2_Rep','Star3_Rep','Star4_Rep']].sum(axis=1)

# Keep numeric features
feature_cols = ['Runtime','IMDB_Rating','Meta_score','No_of_Votes',
                'Certificate_Num','Director_Reputation','Star_Power','Released_Year']

X = df[feature_cols]
y = df['Gross']

X.head()

,Runtime,IMDB_Rating,Meta_score,No_of_Votes,Certificate_Num,Director_Reputation,Star_Power,Released_Year
0,142 min,9.3,80.0,2343110,2.0,8.257142e+07,1.133659e+08,1994.0
1,175 min,9.2,100.0,1620367,2.0,6.936480e+07,3.603600e+08,1972.0
2,152 min,9.0,84.0,2303232,1.0,2.421818e+08,1.200699e+09,2008.0
3,202 min,9.0,90.0,1129952,2.0,6.936480e+07,3.669431e+08,1974.0
4,96 min,9.0,96.0,689845,0.0,3.454000e+07,1.632550e+07,1957.0

In [3]:
X.describe()

,IMDB_Rating,Meta_score,No_of_Votes,Certificate_Num,Director_Reputation,Star_Power,Released_Year
count,1000.000000,843.000000,1.000000e+03,606.000000,9.150000e+02,1.000000e+03,1000.000000
mean,7.949300,77.971530,2.736929e+05,0.938944,6.367443e+07,2.291110e+08,1991.225000
std,0.275491,12.376099,3.273727e+05,0.841821,9.262710e+07,3.663330e+08,23.286662
min,7.600000,28.000000,2.508800e+04,0.000000,1.305000e+03,0.000000e+00,1920.000000
25%,7.700000,70.000000,5.552625e+04,0.000000,4.041448e+06,6.239719e+06,1976.000000
50%,7.900000,79.000000,1.385485e+05,1.000000,2.815654e+07,7.934413e+07,1999.000000
75%,8.100000,87.000000,3.741612e+05,2.000000,8.108480e+07,2.877346e+08,2009.000000
max,9.300000,100.000000,2.343110e+06,2.000000,5.512599e+08,2.914527e+09,2020.000000